### ISSUE TITLE
Git nerd font icon is apparently broken 

### ISSUE THREAD

**Issue by Sweenu** [oh-my-fish/theme-bobthefish#118]
I just activated the nerd fonts for bobthefish. Everything works but the git icon:
![deepinscreenshot_select-area_20171212095424](https://user-images.githubusercontent.com/7051978/33875409-7792a060-df22-11e7-84ee-fbe1cce7d2dd.png)
Was this intended?

**Comment by bobthecow** [comment]
Not intended :)

Which nerd font are you using?

**Comment by Sweenu** [comment]
Oh well, I don't quite know haha. I just installed the whole package with the aur package (nerd-fonts-git) and it installed many fonts. It worked without me having to choose one in particular. How could I change the font? Is it in my terminal emulator settings?

**Comment by bobthecow** [comment]
I don't really know, to be honest. I haven't used Arch in ages.

I would guess that most of the nerd font code points we're using don't exist in your default terminal emulator font, so it looks around until it can find a font that includes them, and ends up finding the right glyphs. But in the case of the git branch icon, something at that code point collides, either in your default font or in some other font that it finds before a nerd font.

If you explicitly set your terminal emulator to use one of the patched fonts, it should all work though.

**Comment by Sweenu** [comment]
Alright, thank you, I'm gonna try as soon as I can and close the issue.

**Comment by Sweenu** [comment]
It was indeed my terminal font.

**Comment by fabiomargarido** [comment]
I think there's something strange going on here indeed. I've used bobthefish since forever and my patched font (InconsolataForPowerline Ner Font) is explicitly set to be used in the terminal. Had no problems.

Today, after running `fisher update`, which brought in around 50 commits for bobthefish, the glyphs in my git indicators suddenly changed (I get the same pencil icon shown in Sweenu's screenshot instead of '*', but the branch glyph is OK).

Let me know if I can provide further info.

**Comment by bobthecow** [comment]
@fabiomargarido can you screenshot yours? i think that's intentional.

**Comment by fabiomargarido** [comment]
I'll screenshot it tomorrow when I'm the office.

But I guess if it's intentional then it's ok, I just didn't see any mention
of this in the readme so I thought it was strange. Can you document how
things should look when using nerd fonts?

Thanks.

Em seg, 5 de fev de 2018 18:05, Justin Hileman <notifications@github.com>
escreveu:

**Comment by fabiomargarido** [comment]
@bobthecow mine looks like this when there are untracked files:

![image](https://user-images.githubusercontent.com/649114/35854147-bd76a886-0b16-11e8-93b0-2fd3f5f31cf4.png)

and when there are unstaged changes:

![image](https://user-images.githubusercontent.com/649114/35854165-c7c77f72-0b16-11e8-9894-b7c074eaaaf0.png)

I guess these make sense and must be correct, I was just put off by the documentation not mentioning this and was mislead by the title in this issue.

Thanks for the awesome work!

**Comment by bobthecow** [comment]
Gotcha. Yeah, the nerd font glyphs changed in #86 / #99, but the last time the screencast in the readme was updated was a year before that :-/

These are the glyphs you should expect :)
