### ISSUE TITLE
name of Master branch not showing up  

### ISSUE THREAD

**Issue by ameenshake** [oh-my-fish/theme-bobthefish#151]
As the title says, the name of the master branch, 'master', is showing up as blank, as you can see below:

![screenshot from 2018-04-20 13-24-46](https://user-images.githubusercontent.com/12386093/39072109-50058bac-449e-11e8-84f4-bc0ac614376c.png)

This is unique to the master branch, all the other branches have their names show just fine:
![screenshot from 2018-04-20 13-28-17](https://user-images.githubusercontent.com/12386093/39072216-b2f07c40-449e-11e8-8b89-ce08754ec621.png)

Any idea what could be causing this?

**Comment by bobthecow** [comment]
Yep! bobthefish prefers not to show the "normal" state for things by default. Rather than "clean", it only shows "dirty". Rather than the number of bg jobs, it shows you a thing only if you have one. Rather than always showing the time to execute a command, it shows only if it takes long enough to be interesting.

For the same reasons, it doesn't show the "master" branch by default, choosing only to show the branch name if it's "interesting".

If you really want it, you can enable it by adding this to your `config.fish`: 

```
set -g theme_display_git_master_branch yes
```

… but I'd highly recommend giving it a shot and seeing if you can live with the opinionated defaults ;)

**Comment by ameenshake** [comment]
How dare you assume what I will need by default in my workflow? What, am I expected to read the documentation now too? Some developers...

(Thanks lol)

**Comment by bobthecow** [comment]
Sure, I'm opinionated. But I'm usually opinionated _and right_ 😘
