### ISSUE TITLE
Prompt is mangled, I'm doing something wrong with fonts probably

### ISSUE THREAD

**Issue by carlisia** [oh-my-fish/theme-bobthefish#162]
![image](https://user-images.githubusercontent.com/16508/42041642-28f635f4-7aa7-11e8-8236-3672aea379bb.png)

I've been trying to fix my prompt problem while using bobthefish and ran out of things to try. I would appreciate if anyone could point me in a productive direction. I've tried setting both nerd and powerline fonts on and both off, and one of them on while the other is off...

My font config:

![image](https://user-images.githubusercontent.com/16508/42041717-5221cf92-7aa7-11e8-8a9a-a83042901d42.png)

**Comment by bobthecow** [comment]
Older powerline patched fonts put the glyphs at different code points. I imagine Agnoster is using those old code points rather than the current set, as is the font you’ve got installed?

I’d suggest using one of the pre-patched nerd fonts (and enabling the theme option for bobthefish while you’re at it 🙂)

http://nerdfonts.com/

**Comment by carlisia** [comment]
Cool, thanks a bunch @bobthecow. I will try one of those specific fonts. Also, I just found what the problem is:

![image](https://user-images.githubusercontent.com/16508/42042854-e9f34f06-7aa9-11e8-8ab9-9256b644d497.png)

I commented out the base16 config and it looks ugly now but it works. I'll figure it out from here. Closing!

**Comment by carlisia** [comment]
Reopening this and will close right after, but in case it helps anyone:

Fixed by using one of those nerd fonts and adding back the commented out code above.

Thank you!
