### ISSUE TITLE
Very slow on hg repositories

### ISSUE THREAD

**Issue by ruipacheco** [oh-my-fish/theme-bobthefish#177]
Pressing enter on a prompt in a normal directory is obviously fast. 
Pressing enter on a prompt in a directory with a git repo, is noticebly slow. 
Pressing enter on a prompt in a directory with a mercurial repo takes almost a second to complete.

Some people have git/hg repos inside git/hg repos...

I can confirm that it takes 2 seconds for the prompt to return on a mercurial repository while it is sub second on a git repo or a folder without repositories.

**Comment by ruipacheco** [comment]
I re-installed bobthefish today and the issue seems to have mostly gone away, ie, performance is equally slow for git and hg and better than before. Is there more work to be done or is this as good as it gets and I can close the issue?

**Comment by bobthecow** [comment]
I'm really not sure. Both git and hg _can_ get slow, and there's not a ton bobthefish can do about it. For example, I've got a work repo that regularly takes 30+ seconds to run `git status` :-/ 

There are some workarounds in bobthefish for hg, to ensure that it only runs in folders which _could_ be mercurial repos, which helps limit the potential for slowness. But it doesn't do much to speed things up if you're actually in a slow mercurial repo, unfortunately.

We do have a handful of ways to speed up bobthefish inside large git repos (such as supporting per-repo disabling of the "dirty" flag, which tends to be the slowest part in git). It might make sense to add support for overrides like this in mercurial, as well.

Other than that, you always have the option of disabling vcs support completely for paths that are really slow:

```
set -g theme_vcs_ignore_paths /some/path /some/other/path{foo,bar}
```

**Comment by ruipacheco** [comment]
I'll close it for now then.

**Comment by bobthecow** [comment]
Sounds good.

If you run into a repo that's particularly slow, and don't mind doing some debugging, it'd be helpful to know which parts are slow for you so we could do some optimization or allow overrides :)

**Comment by kunickiaj** [comment]
Ran into a similar issue, so did some debugging and for me, the issue is around this line https://github.com/oh-my-fish/theme-bobthefish/blob/626bd39b002535d69e56adba5b58a1060cfb6d7b/functions/fish_prompt.fish#L996 to determine whether or not the tree is dirty. 

For the large repo, you can disable showing untracked files with `git config bash.showUntrackedFiles false` which greatly sped things up for me. Note that enabling this flag means you must know what files need to be added as git won't tell you which are untracked anymore.

**Comment by kunickiaj** [comment]
Replicating a feature like this would be really nice, so that long running commands for retrieving git status (or others) don't slow down the prompt from displaying: https://github.com/romkatv/powerlevel10k#why-does-git-status-sometimes-appear-grey-and-then-gets-colored-after-a-short-period-of-time

In p10k, it's also likely gitstatusd integration also speeds things up.
