### ISSUE TITLE
fundle compatibility

### ISSUE THREAD

**Issue by Perlence** [oh-my-fish/theme-bobthefish#18]
The theme is displayed incorrectly when installed with [fundle](https://github.com/tuvistavie/fundle):

```fish
fundle plugin 'oh-my-fish/theme-bobthefish'
```

![screenshot - 12172015 - 11 42 18 am](https://cloud.githubusercontent.com/assets/1044300/11865936/89ca0a3a-a4b8-11e5-9f4c-3ba75e6221ec.png)

It can be fixed by moving all fish sources to `functions` subfolder.

**Comment by bobthecow** [comment]
Yes, but that breaks oh-my-fish compatibility ;)

**Comment by tuvistavie** [comment]
The easiest way to add compatibility to fundle without breaking anything (AFAIK) is

* Add an empty `init.fish` in the root directory (this will prevent fundle from [loading all the files in the directory](https://github.com/tuvistavie/fundle/blob/master/functions/fundle.fish#L199))
* Create a symlink from root dir to functions (i.e. `ln -s . functions` from the top directory)

From what I have checked of oh-my-fish loading process, it should not be an issue.
As this theme is popular, it would be great if you could add compatibility as it would avoid maintaining a fork. Thanks!

**Comment by bpinto** [comment]
@tuvistavie I'd like it to be compatible with fundle too. I have seen your framework and I like it, it's simple as reminds me of the previous OMF version. You've done a great job there. :+1:

**Comment by bobthecow** [comment]
@bpinto seems like the best thing to make this sort of thing possible would be to add `functions` folder support to omf themes?

**Comment by bpinto** [comment]
Would you make another github script to update all themes to follow that pattern?

**Comment by tuvistavie** [comment]
@bpinto @bobthecow Thank you very much for your help and consideration! Please let me know if there is anything I can help with!

**Comment by bobthecow** [comment]
@bpinto yeah, probably sometime this weekend?

**Comment by bpinto** [comment]
@bobthecow :+1:

**Comment by bucaran** [comment]
@Perlence @tuvistavie @bobthecow 

The problem is inside `theme-bobthefish/fish_prompt.fish`. [This](https://github.com/oh-my-fish/theme-bobthefish/pull/19) PR fixes it without breaking OMF compatibility.

Basically you are not declaring `__bobthefish_*` variables as global variables, but local to the current scope (which would be indeed global if you were sourcing the `fish_{,right}prompt.fish` from your command line. I haven't looked at fundle in depth, but I just tested with the following:

```
fundle plugin 'bucaran/theme-bobthefish'
fundle install
```

And it works of course:

<img width="922" alt="screen shot 2016-01-02 at 4 33 20 pm" src="https://cloud.githubusercontent.com/assets/8317250/12073675/91c9708c-b16e-11e5-9a8c-729d0c1ba3e6.png">

**Comment by bpinto** [comment]
The solution to this problem is to move the theme functions to the `functions` folder.

**Comment by millaisnick** [comment]
Hi all. I started using fundle and would really like to use this theme or agnoster.

**Comment by bobthecow** [comment]
This theme should now work everywhere. Please let me know if you run into any more problems.

**Comment by tuvistavie** [comment]
It seems to work great, thank you very much for your help!

**Comment by bobthecow** [comment]
👍

**Comment by Perlence** [comment]
Works now, thanks :+1:
