### ISSUE TITLE
nerd font doesn't render properly

### ISSUE THREAD

**Issue by deimosfr** [oh-my-fish/theme-bobthefish#194]
Hi,

First of all, sorry about the question, I'm a newbie with fonts management. I'm running Arch Linux with Terminator, I've installed nerd-fonts-complete AUR package and can see fonts in Terminator.

The powerline version works:
![Powerline](https://user-images.githubusercontent.com/2962805/54242502-26e29200-4525-11e9-9d49-bbbbd2180db2.png)
However while trying to activate nerd font, the result is not there:
```
set -g theme_powerline_fonts no 
set -g theme_nerd_fonts yes
```
![nerd](https://user-images.githubusercontent.com/2962805/54242609-8640a200-4525-11e9-8ef1-12734801f9de.png)

Any idea what I'm doing wrong?

Thanks

**Comment by bobthecow** [comment]
Oh! Leave `theme_powerline_fonts` on :)

**Comment by deimosfr** [comment]
Thanks, not obvious but thanks

**Comment by bobthecow** [comment]
I’ll make it so nerd fonts being enabled takes precedence over disabling powerline fonts.

**Comment by Shub1427** [comment]
@bobthecow I am facing the issue as well, but prompt is totally broken

![image](https://user-images.githubusercontent.com/11786283/71304046-e171c000-23e6-11ea-8173-e4d130b87242.png)

I have nerd-fonts installed, `theme_powerline_fonts` set to yes. tested the theme both in KDE Konsole and Alacritty (currently I am using Alacritty). 

Theme `budspencer` works fine with same Alacritty config, though I am not using it because it has it's own weird issue with padding and paste.
![image](https://user-images.githubusercontent.com/11786283/71304097-d2d7d880-23e7-11ea-80a1-8f215f3f087c.png)


Output of `omf doctor`

```
Oh My Fish version:   6
OS type:              Linux
Fish version:         fish, version 3.0.2
Git version:          git version 2.24.0
Git core.autocrlf:    no
Your shell is ready to swim.
```

**Comment by ArghyaSarkar** [comment]
I am having similar problem to @Shub1427. Screenshot attached below.

<img width="586" alt="Screenshot 2020-04-28 at 9 25 04 PM" src="https://user-images.githubusercontent.com/8719838/80509279-d3383f80-8996-11ea-8535-c3abdd9ebbfb.png">

Weird thing is when I use 
```
set -g theme_powerline_fonts no 
``` 
the prompt renders fine. @Shub1427 can you check if yours is behaving similarly?

**Comment by bobthecow** [comment]
With `theme_powerline_fonts` off, it's not using any powerline characters, so it _should_ render just fine :)

**Comment by chephei** [comment]
how can i change the red tag language? i use fish and omf with nerd fonts
![image](https://user-images.githubusercontent.com/31193948/129483923-503668d7-742e-45e8-921d-d82cd920354e.png)
