### ISSUE TITLE
How can I the theme I am using?

### ISSUE THREAD

**Issue by SkylerLS** [oh-my-fish/theme-bobthefish#209]
Hello,

I'm using fish in iTerm2 as my shell.
I just got a new computer and want to emulate my shell.
If I run `bobthefish_display_colors`, the output looks like this:
<img width="456" alt="Screen Shot 2019-07-19 at 4 42 56 PM" src="https://user-images.githubusercontent.com/21369525/61564445-78a3a780-aa44-11e9-8b4e-aff58cb0d4f9.png">

However those colours don't quite match the colours outlined in the themes on the README on the main page of the repo. Where can I find the theme I'm using? It's been so long since I set it up that I don't recall.

I checked my config.fish and nothing about my bobthefish theme is in there.

If anyone could let me know where to find this theme that would be great.

**Comment by SkylerWittman** [comment]
I figured it out, sorry bout that.
Command is `set --show theme_color_scheme`

**Comment by bobthecow** [comment]
they didn't quite match because colors are all approximate, since they're being mapped back to 256 colors (or fewer) by your terminal.

it's probably worth adding the value for `theme_color_scheme` (and whether you're using a custom color scheme function) to the output of `bobthefish_display_colors`. Let's keep this ticket around as a feature request :)
