### ISSUE TITLE
vi mode not changing in prompt

### ISSUE THREAD

**Issue by lightcap** [oh-my-fish/theme-bobthefish#248]
I don't know when it stopped working unfortunately, but the vi segment doesn't change when switching vi modes anymore. It aways shows insert mode, even when I'm clearly in normal.

**Comment by bobthecow** [comment]
I think the latest fish release stopped re-rendering the main prompt when the bind mode changes. I'll take a look.

**Comment by bobthecow** [comment]
Okay, I've got a fix. Unfortunately this means we lose the pretty arrow between it and the rest of the prompt (and it has to move to the left of the status / superuser / jobs flags):

<img width="762" alt="Screen Shot 2020-04-20 at 9 54 28 AM" src="https://user-images.githubusercontent.com/53660/79778268-54d00380-82ed-11ea-935b-2c53e6191069.png">

**Comment by lightcap** [comment]
@bobthecow confirmed it's fixed! Thanks.

Does suck that the arrow disappears though.

Is the lack of re-rendering a bug in fish we should report?

**Comment by lightcap** [comment]
Possibly related to https://github.com/fish-shell/fish-shell/issues/5783?

**Comment by bobthecow** [comment]
Yep, definitely caused by that. And to be clear, I think that change is the right thing to do.

Making the shell hang for as long as it takes to redraw the entire prompt every time you toggle input modes isn’t really acceptable, even if it’s only a couple hundred millisecond delay. With really rich prompts, like bobthefish, it could be even longer than that. 

I’m sad to lose the arrow as well. But I think it’s a net win, and maybe we’ll come up with a good way to make the arrow work when redrawing the mode indicator. But for now, it’s better to be right and less beautiful than to be wrong :)
