### ISSUE TITLE
Setting LANG, LC_ALL results in questions marks

### ISSUE THREAD

**Issue by EdGue42** [oh-my-fish/theme-bobthefish#261]
I added 

`set -x LANG   "C"`
`set -x LC_ALL "C"`

to my fish.config in order to fix some issues when using the shell with some remote systems that need these settings for python (?) to work properly. 

After adding these two sets, bob shows me that infamous "question mark" prompt:

![image](https://user-images.githubusercontent.com/53468311/89261026-a6e32d80-d62d-11ea-9e20-21073efedf42.png)

Notes:

- The actual culprit is **LC_ALL**, setting LANG alone doesn't lead to this problem
- I **am** using a powerline font, see my shell _without_ the above settings for LC_ALL

![image](https://user-images.githubusercontent.com/53468311/89261098-cd08cd80-d62d-11ea-84fa-0cead93856d4.png)

**Comment by bobthecow** [comment]
Yep, this is expected. The POSIX ("C") locale doesn't support anything outside of ASCII characters, and powerline characters are definitely that. Ideally the fix for this is to stop using the POSIX locale. No modern system should need that :( 

Otherwise, you can disable powerline support in bobthefish, and it'll fall back to only ASCII characters. Add this to your fish config:

```
set -g theme_powerline_fonts no
```

**Comment by EdGue42** [comment]
Thanks for the quick response and helpful explanation!
