### ISSUE TITLE
Strange vertical lines on either side of git symbol

### ISSUE THREAD

**Issue by dyspr0sium** [oh-my-fish/theme-bobthefish#279]
Hi,

I'm seeing a strange red and green line on either side of the git symbol, where the arrow symbols are:
![Screenshot from 2020-10-22 14-18-05](https://user-images.githubusercontent.com/33480365/96820445-baa27100-1471-11eb-93dd-c9a8ae09cceb.png)
They don't appear on the arrow when the working directory is not a git repo. It appears regardless of which font I use (default Ubuntu Monospace or UbuntoMono Nerd Font), and various permutations of theme_powerline_fonts/theme_nerd_fonts yes/no and theme_color_scheme.

Any idea on how to make them go away?

**Comment by bobthecow** [comment]
They probably appear anywhere the prompt has multiple colored segments in it, though they might be more noticeable with certain colors.

They're a rendering artifact, caused by the fact that the "body" of each segment uses terminal background colors, and the "point" uses foreground colors. Certain terminal apps, certain color schemes, and certain settings, seem to make them better or worse. 

I don't think I've seen the red/green lines though. My guess is that they're related to subpixel-antialiasing.

What terminal app, OS, desktop manager, etc are you using?

**Comment by dyspr0sium** [comment]
I'm on Ubuntu 20.04.1, using the default GNOME.

You were spot on; I changed Antialiasing from "Subpixel (for LCD screens)" to "Standard (grayscale)" using gnome-tweaks and the issue was resolved. Thanks!

**Comment by bobthecow** [comment]
Great! Glad I could help 🙂
