### ISSUE TITLE
Either Bobthefish or omf error?!

### ISSUE THREAD

**Issue by Dan1jel** [oh-my-fish/theme-bobthefish#287]
Sometimes when I use an command for ex "scp user*server:/test/folder/file.txt ." And in this example, say the file name is file1.txt"

I press the button "up" to get my last command, but when I edit "file" to "file1" i see an text error in ex server looking lien this  -> 

"scp user*srver:/test/folder/file1.txt ."

When I edit to correct "server" and run the command, the server is with 2 "ee". Is this theme wise or maybe omf error? 

I use fish, omf and Bobthefish on my phone with termux.

**Comment by bobthecow** [comment]
This sounds like either Fish or your terminal emulator forgetting how wide the line is during redraw. My money is on Termux, as I've never seen this issue personally. 

The bug is almost certainly not in bobthefish, though it is probably triggered by our heavy use of weird characters. You could confirm by disabling powerline and geekfonts support. That should make everything fall back to ascii, and I bet your issue goes away.

As far as fixing it for good, maybe look for a setting like "treat ambiguous characters as full width" in Termux?

**Comment by Dan1jel** [comment]
Thank you for the reply. Yes I do.thin it's termux not really compatible with fish or other things completely. Buy i will see if I can find anything regarding you tips, thanks so för and helping me where to look :) i get back to this topic when I find an answer.

**Comment by Dan1jel** [comment]
An issue have been done on termux github, this one can be closed because I think this is not related to this awesome theme. Hope they solve this rather soon (using bash for now untill this is fixed.) 

https://github.com/termux/termux-app/issues/1860
