### ISSUE TITLE
Suspend (CTRL-z) and close running CLI (CTRL-c) and various other behaviors causes "Copy to Clipboard" behavior to trigger

### ISSUE THREAD

**Issue by andrew-enquanta** [oh-my-fish/theme-bobthefish#370]
Using the most recent bobthefish from omf on macOS, I get the following unwanted behaviors:

Suspend (CTRL-z)
close running CLI (CTRL-c)
piping anything to pbcopy

These all copies current path to clipboard.

I know it is bobthefish causing this because it immediately goes away when I `omf remove bobthefish`.

Please let me know if there is any other logging I can provide.

Thanks

**Comment by bobthecow** [comment]
weird. i literally have no idea how that's happening.

what terminal are you using?

**Comment by andrew-enquanta** [comment]
iTerm 2 (3.5.2) + tmux (3.4)

**Comment by andrew-enquanta** [comment]
Maybe `fish_clipboard_copy` is getting called? running this in the terminal on its own copies the current path.

**Comment by bobthecow** [comment]
https://github.com/oh-my-fish/theme-bobthefish/commit/0c15ff1cbc4bfa026c882e01dd5ceec327f26033#commitcomment-144040411 this is helpful!

what fish version are you running? do you have a path builtin?

**Comment by andrew-enquanta** [comment]
`fish, version 3.7.1`

I did have a custom fish function called `path` which did `pwd | pbcopy`, but this problem persists even after I got rid of the custom function.

Otherwise, I don't quite know what you mean by "path builtin".

**Comment by bobthecow** [comment]
that sounds an awful lot like the culprit, to be honest. run `type -t path`

**Comment by bobthecow** [comment]
If I'm right, I just pushed a change that will fix your issue. Give it a shot?

**Comment by andrew-enquanta** [comment]
This fixed it! Thank you

**Comment by bobthecow** [comment]
Great to hear! 

You should probably consider renaming your "copy the path" function to something that doesn't collide with a fish builtin :)

**Comment by bobthecow** [comment]
Hey @andrew-enquanta, I’m going to need to revert this change; it turns out builtins are checked at parse time, not runtime, so making a conditional builtin call just breaks it for anyone who doesn’t have that builtin. See #371 for more info. 

Given that LTS linux versions ship with Fishes too old for a `path` builtin, i’m going to need to revert this change.

I’ll keep looking for other workarounds, but at this point I think the proper fix is a very strong suggestion that you not have functions named the same thing as builtins :)

**Comment by andrew-enquanta** [comment]
Copy that. thanks for the update
