### ISSUE TITLE
Last arrow color

### ISSUE THREAD

**Issue by DONSA** [oh-my-fish/theme-bobthefish#9]
Hi,

If you notice, the color of the last arrow icon in each line is always more light. The color is a little bit different.
This is a bug or a configuration problem?
I'm on a Macintosh.

Thanks

<img width="783" alt="screen shot 2015-09-22 at 4 44 36 pm" src="https://cloud.githubusercontent.com/assets/4755300/10026262/99e30faa-6158-11e5-9ebe-b974ecfcf789.png">

**Comment by bobthecow** [comment]
It's either transparency or "minimum contrast" issues with your terminal, or possibly a combination of the two.

It happens because the tips of arrows are characters, while the body of arrows are a background color. Terminal applications play fast and loose with how they apply color to the background. For example, some make explicit background colors non-transparent, while others make them the same opacity as the rest of the window. iTerm, in particular, gets wonky when you set a "minimum contrast" setting, which it accomplishes by brightening or darkening the background color of any character that doesn't meet your contrast threshold.

**Comment by DONSA** [comment]
Well, that means that there's nothing I can do because terminal apply the color to background differently.

Thanks anyway

**Comment by bobthecow** [comment]
Yeah, sorry :)

**Comment by bobthecow** [comment]
Oh, yes! That was added later, and I use it as well. Thanks for updating this issue :)
